[package]
name = "bb"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = { version = "0.29.0", default-features = false, features = ["termwiz"] }
termwiz = "0.23.3"
